version: '3.7'

services:
  backend:
    image: backend
    ports: 
      - "3001:8080"
        #    command:
        #"bash -c env/bin/python3 run.py"

  frontend:
    image: frontend
    ports:
      - "5001:3000"
        #command:
        #"bash -c npm start"
