"""Mudar descrição de animals de desc para description

Revision ID: 457525ab12ce
Revises: 
Create Date: 2021-07-04 17:04:55.184615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457525ab12ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('description', sa.Text(length=500), nullable=True))
    op.drop_column('animals', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('desc', sa.TEXT(length=500), nullable=True))
    op.drop_column('animals', 'description')
    # ### end Alembic commands ###
