"""Initial migration.

Revision ID: 475f29ef6787
Revises: 
Create Date: 2021-06-20 22:13:47.734756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475f29ef6787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_org', sa.Column('telephone', sa.String(length=16), nullable=True))
    op.add_column('auth_org', sa.Column('website', sa.String(length=64), nullable=True))
    op.add_column('auth_org', sa.Column('donation_url', sa.String(length=64), nullable=True))
    op.add_column('auth_org', sa.Column('desc', sa.Text(length=500), nullable=True))
    op.add_column('auth_user', sa.Column('telephone', sa.String(length=15), nullable=True))
    op.add_column('auth_user', sa.Column('description', sa.Text(length=500), nullable=True))
    op.drop_column('auth_user', 'role')
    op.drop_column('auth_user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('status', sa.SMALLINT(), nullable=False))
    op.add_column('auth_user', sa.Column('role', sa.SMALLINT(), nullable=False))
    op.drop_column('auth_user', 'description')
    op.drop_column('auth_user', 'telephone')
    op.drop_column('auth_org', 'desc')
    op.drop_column('auth_org', 'donation_url')
    op.drop_column('auth_org', 'website')
    op.drop_column('auth_org', 'telephone')
    # ### end Alembic commands ###
