"""Add relationship between Org and Animal and add Access variable

Revision ID: 92adc9dc7166
Revises: 475f29ef6787
Create Date: 2021-06-20 22:16:34.443575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92adc9dc7166'
down_revision = '475f29ef6787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('access', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'access')
    # ### end Alembic commands ###
